config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: 'organizations#index'
  get ':id', to: 'organizations#show', as: 'organization'
  get ':organization_id/tickets/:id', to: 'tickets#show', as: 'ticket'
  namespace :auth do
    resources :organizations, only: [:show]
    resources :pools, only: [:show, :new, :create] do
      resources :lanes do
        member do
          post 'move_left'
          post 'move_right'
        end
      end
      resources :tickets do
        member do
          post 'move_left'
          post 'move_right'
        end
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lane.rb
class Lane < ApplicationRecord
  belongs_to :pool
  acts_as_list scope: :pool

  has_many :tickets, dependent: :destroy

  before_destroy :minimum_one_lane, prepend: true

  # make sure each pool has at least one lane
  def minimum_one_lane
    self.pool.lanes.count > 1 ? true : false
  end
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :users, dependent: :destroy
  has_many :pools, dependent: :destroy
  has_many :tickets, dependent: :destroy

  extend FriendlyId
  friendly_id :name, use: :slugged

  validates :name,
    presence: true,
    uniqueness: true
  
end

app/models/pool.rb
class Pool < ApplicationRecord
  belongs_to :organization
  has_many :lanes, -> { order(position: :asc) }, dependent: :destroy
  has_many :tickets, dependent: :destroy

  validates :name,
    presence: true,
    uniqueness: { scope: :organization, case_sensitive: false }

  after_create :generate_lane

  def generate_lane
    self.lanes.create(name: 'First')
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :pool
  belongs_to :lane
  belongs_to :organization

  validates :public_label,
    presence: true,
    uniqueness: { scope: :organization }

  extend FriendlyId
  friendly_id :public_label, use: :slugged

  before_validation :generate_label, :on => :create, prepend: true

  def generate_label
    self.public_label = CouponCode.generate
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :organization
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected
  
  def after_sign_in_path_for(resource)
    auth_organization_path(resource.organization_id)
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  def index
    @organizations = Organization.all
  end

  def show
    @organization = Organization.friendly.find(params[:id])
    @tickets = []
    if params[:search] && !@organization.blank?
      @tickets = Ticket.all.
        joins(pool: :organization).
        where('organizations.id = ?', @organization.id).
        where("tickets.public_label ILIKE ?", "%#{params[:search]}%").
        limit(20)
    end
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  def show
    @organization = Organization.friendly.find(params[:organization_id])
    @ticket = @organization.tickets.friendly.find(params[:id])
    @pool = @ticket.pool
    @lanes = @pool.lanes.order('lanes.id ASC')
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bronze Board</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div id='layout-container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/organizations/index.html.erb
<div>
  <div>
    <%= link_to 'Log In', user_session_path %>
  </div>
  <div>
    <% @organizations.each do |org| %>
      <%= link_to "#{org.name}", organization_path(org.slug), class: 'primary-button' %>
    <% end %>
  </div>
</div>

app/views/organizations/show.html.erb
<div>
  <h3><%= @organization.name %></h3>
  <%= form_tag organization_path(@organization.slug), :method => 'get' do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %>
  <div>
    <h2>Results</h2>
    <% @tickets.each do |ticket| %>
      <%= link_to "#{ticket.public_label}", ticket_path(@organization.slug, ticket.slug), class: 'primary-button' %>
    <% end %>
  </div>
</div>

app/views/tickets/show.html.erb
<div>
  <%= link_to "back", :back %>
  <h4><%= @pool.name %></h4>
  <h3><%= @ticket.public_label %></h3>
  <% @lanes.each do |lane| %>
    <% if lane.id == @ticket.lane_id %>
      <h3><%= lane.name %></h3>
    <% else %>
      <p><%= lane.name %></p>
    <% end %>
  <% end %>
</div>